__author__ = "Jia Jia"
__author_email__ = "angersax@sina.com"
__description__ = "Gerrit Action"
__license__ = "Apache-2.0"
__title__ = "gerritaction"
__url__ = "https://github.com/craftslab/gerritaction"
__version__ = "1.3.0"
